name: Keep Render App Awake

on:
  schedule:
    - cron: '*/6 * * * *'  # кожні 6 хвилин
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render health endpoint
        run: curl -sSf https://exam-clinic-api.onrender.com/health || echo "Ping failed"